language: scala

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"

scala:
- 2.11.8

jdk:
- oraclejdk8

script:
- sbt clean coverage test package
# Trick to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm

notifications:
  email:
    recipients:
    - revolistion@autoscout24.com
  slack: scout24:R2Wa8ST4UlL271lKbJU9tAF8
    on_success: change
    on_failure: always

after_success:
  - >
      sh "$TRAVIS_BUILD_DIR/travis-ci-coveralls-token.sh" &&
      sbt coverageReport coveralls &&
      sh "$TRAVIS_BUILD_DIR/travis-ci-bintray-credentials.sh" &&
      sbt publish